server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Dòng mấu chốt để sửa lỗi 404 khi reload đây rồi:
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình trang lỗi mặc định (tùy chọn)
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}